# Docker compose file for initializing gesture pointer environment
# 
#   - Ubuntu 24.04 Noble 
#   - ROS2 jazzy 
#

services:
  gesture_pointer:
    tty: true 
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: gp_container    # identifier
    network_mode: host
    ipc: host
    pid: host
    volumes:
      - ./ros2env/src:/up/ros2env/src           # bind the directories 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw        # enable cv2 tools 
    devices: 
      - /dev/video4:/dev/video4                 # for camera usage
      - /dev/video5:/dev/video5                 # for camera usage
      - /dev/video6:/dev/video6                 # for camera usage
      - /dev/video7:/dev/video7                 # for camera usage 
      - /dev/video8:/dev/video8                 # for camera usage
      - /dev/video9:/dev/video9                 # for camera usage 

    environment:
      - DISPLAY=$DISPLAY    # env. variable for display, needed for e.g., RViz
volumes: 
  gp_container:
